# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lpbwce <- function(y, x, K, L, res, c, p, q, h, b, deriv, fact) {
    .Call(`_nprobust_lpbwce`, y, x, K, L, res, c, p, q, h, b, deriv, fact)
}

